### ISSUE TITLE
Planner timeline only render link per preview mode, not include actual link text as well?

### ISSUE THREAD

**Issue by RobColes** [ivan-lednev/obsidian-day-planner#100]
Love the planner!
I have a bunch of To-Dos which have links to somewhere else. e.g. today I have:
- [ ] 12:30 [Sitecore 10 Doc. Next: PoC doc, Solution Design](evernote:///view/13373/s1/1acbefe0-a3c6-a9fd-4640-5c5576cb5600/1acbefe0-a3c6-a9fd-4640-xxxxxxxxxxxx/)
The planner shows all of this, but it is not clickable and isn't helpful. 
Is it possible just to render the link in the planner as it appears in Obsidian preview mode - just the square bracket bit? Or have it as an option?

**Comment by willypicard** [comment]
I fully agree with RocColes. It would be indeed great to have links within the Planner timeline as links, instead of the text of the link. I often use alias links that are rather long (such as [[ Report - Data Ingestion - 2021_12_12 | data ingestion ]]) and it does not look nice in the Planner timeline.

**Comment by ivan-lednev** [comment]
Closing this as stale.
