### ISSUE TITLE
Feature Request -- Outlook support

### ISSUE THREAD

**Issue by aparente-nurix** [ivan-lednev/obsidian-day-planner#119]
Outlook calendar support would be amazing!

**Comment by tobiasbueschel** [comment]
+1 on this, this would be a great option to simplify daily notes and meeting note taking :)

Here's one example of how this could work (for my use case):

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/13087421/161809952-7b58c1eb-49b0-4fb8-bced-44f391ecdc63.png">

@lynchjames have you looked into this already? Once I'm more familiar with Obsidian plugin development, would be happy to help with the implementation!

**Comment by greenbereth** [comment]
@tobiasbueschel 
Thanks for the screenshot and pre-work

**Problem statement:**
Planning and scheduling my day takes additional effort, because my calendar and my task management and note view is not aligned. I need to switch between calendar (caldav, MS Exchange) and my tasks and notes (Obsidian with day planner) to copy+paste my times.
Every day this costs me around 2 to 5 Minutes.
Additionally, changes or invites in calendars are not up-to-date. Thus, I rely more on my calendar than on day planner and spent less time there.

**Aspects (for me to be successful):**
- [ ] integration to Microsoft Exchange and CalDav
- [ ] update interval 15minutes  (manually is a plus)

**Success Criteria**
- Save 5 Minutes effort per day
- spent 80% of planning / scheduling activity in Obsidian (with day planner) and 20% in calendar (e.g. to schedule meetings)

There are probably more great value adding functionality like placing specific calendar items in specific places in the note (as shown by @tobiasbueschel ), yet this extends (for me) the core functionality of having calendar items in the calendar.

Thanks a lot for the great work you provided so far for Day Planner

**Comment by FeralFlora** [comment]
This can be done using the ICS plugin. See: https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74

**Comment by ivan-lednev** [comment]
This is available since 0.19.0, see [README](https://github.com/ivan-lednev/obsidian-day-planner?tab=readme-ov-file#showing-internet-calendars)

**Comment by tobiasbueschel** [comment]
Thanks @ivan-lednev two questions on this:

1. Is there any way to integrate a calendar in Outlook (e.g., on Windows or macOS) that is not publicly shared?

> [Note: Published calendars are viewable by anyone with the link to the calendar.](https://support.microsoft.com/en-us/office/introduction-to-publishing-internet-calendars-a25e68d6-695a-41c6-a701-103d44ba151d)

2. Is there any way to automatically create notes or headings for calendar events?

**Comment by ivan-lednev** [comment]
Hello, @tobiasbueschel,

> Is there any way to integrate a calendar in Outlook (e.g., on Windows or macOS) that is not publicly shared?

Your calendar is publicly shared only if the public has a link to it. If you don't share the link, it's not public.

> Is there any way to automatically create notes or headings for calendar events?

If you'd like to have something like that, please create a separate issue and describe in detail the workflow you'd like to have with this.

**Comment by tobiasbueschel** [comment]
Thanks @ivan-lednev my first question was not about how public calendars work - I'm aware that only someone who has the link would have access to it. However, I'd like to avoid publishing my calendar to a public URL altogether.

Hence, my question was rather - how can I use a **private** calendar with `obsidian-day-planner` extension? Currently, it seems to only support it for **public** calendars.

**Comment by ivan-lednev** [comment]
> Hence, my question was rather - how can I use a private calendar with obsidian-day-planner extension? Currently, it seems to only support it for public calendars.

This is not currently implemented. I think for this I'd need to implement some kind of authorization, and, as you understand, this is a completely different level of complexity.
