### ISSUE TITLE
Pomodoro Integration?

### ISSUE THREAD

**Issue by ispringle** [ivan-lednev/obsidian-day-planner#171]
Not an issue, just a confusion maybe. The description of this plugin mentions pomodoro, but I am at a loss on how this app integrates with pomodoros at all.

> This repository contains a plugin for [Obsidian](https://obsidian.md/) for day planning and managing pomodoro timers from a task list in a Markdown note.

I read all the docs I could find on this plugin but am still not sure how I manage my pomo timers with this day-planner.

**Comment by lukemt** [comment]
Well, as I understand it, you can schuedule your day as you like and if you enter 25/5 lengths of tasks you essentially created your own pomodoro schedule with progress bar in the status bar and system notification when ever a task/pomodoro is done.

But It's more flexible than this. You can define your schedule to your liking.

In order to schedule pomodoros you just enter something like this:
```markdown
- [x] 16:00 pomodoro: working on something
- [x] 16:25 BREAK
- [ ] 16:30 pomodoro: Researching about the day planner extension
- [ ] 16:55 BREAK
- [ ] 17:00 pomodoro...
- [ ] 17:25 END
```

**Comment by Nachiten** [comment]
> 

I am with @pard68  on this one. When you think of pomodo integration you certainly dont think of having to do it manually. You think of something that you tell it what task you want to do, and then it generates the pomodoro intervals automatically with some seting. Example: 25 work time, 5 mins rest. 

So I also think something more explicit related to pomodoro should be intergrated, or remove the word pomodoro from the readme, as it is confusing.

**Comment by ivan-lednev** [comment]
Closing this as stale.
