### ISSUE TITLE
Auto complete past tasks is gone

### ISSUE THREAD

**Issue by aknighty74** [ivan-lednev/obsidian-day-planner#224]
It's good news to know that we finally got a fork of this old project and a lot of new features. However, features like auto complete past tasks is not working. Also, the line/bar is barely visible since it is behind the current task on the timeline, verified this with multiples themes.

**Comment by ivan-lednev** [comment]
Hey, @aknighty74. Do you expect to see the time indicator above task-blocks? Or to have these margins wider?
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/b8f511d5-1255-4644-9308-ddd6110b5aaf)

**Comment by JosephBrooksbank** [comment]
I would expect to see that above the task-blocks, personally

**Comment by aknighty74** [comment]
> Hey, @aknighty74. Do you expect to see the time indicator above task-blocks? Or to have these margins wider? ![image](https://user-images.githubusercontent.com/41428836/264703941-b8f511d5-1255-4644-9308-ddd6110b5aaf.png)

yes, both actually would do the trick

**Comment by ivan-lednev** [comment]
After thinking about this, I've decided not to implement this, since `completed` and `past` are two different task states that I'd like to keep separate.

Of course, if someone wants to submit a PR, adding this as an opt-in feature, I'll be happy to merge it.

**Comment by aknighty74** [comment]
In the mean time (if possible) can you make the timeline bar a bit more visible as @JosephBrooksbank stated. Should I open a separate issue for this?

**Comment by JosephBrooksbank** [comment]
I can take a crack at that today

**Comment by JosephBrooksbank** [comment]
This is a bit harder of a problem than I imagined, due to how stacking works. Getting the time indicator on top is trivial, but then it also goes over the text in the tasks, which doesn't look great either: 
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/6687530/84514a0a-754f-42a3-8352-260f47538b85)

To get it above the background of the task but below the text seems more difficult, because stacking is only relevant to the _parent_ element. 
```
<div> time indicator </div>
<div task
   <ul list items />
</div
```
The 'time indicator' can only be 'stacked' with the entire task object, because they are siblings. elements internal to the task element cannot stack with the time indicator independently. To get it to stack one and not the other will require a more complicated solution, I think.

**Comment by MaxwellVale** [comment]
Is the autocomplete event feature not available?

**Comment by ivan-lednev** [comment]
Closing this as not planned, since a 'past' task is conceptually different from a 'completed' one.
