### ISSUE TITLE
Move from "daily planner" > planner 

### ISSUE THREAD

**Issue by dxcore35** [ivan-lednev/obsidian-day-planner#25]
There will be huge benefits if user can plan days, weeks or month ahead....
The current approach to plan the day is bit not productive and as I would like to use the plugin and Obsidian for Task planning and management it is not currently suiting me. Things, features, concepts to consider:
- switch philosophy of daily planner to just planner
- ability to plan the days, weeks, months ahead 
- ability to add recurring tasks (with various settings of reoccurring)
- ability to reschedule task (either by keyboard shortcut) or by adding - [ ] Task1 `> {2020-07-20-18:00}`
- ability to auto-link to original source of rescheduled task `- [x] Task1 [[2020-21-20|BlockID]]`
- ability to create tasks with no fixed time (if not marked as DONE, they will auto-append next day)
- ability to show whole one month at glance (Please lisen to [this podcast ](https://www.listennotes.com/embedded/e/5badffd069d64a489e770190a76d3642/) especially around 1:04:17)
- please do not hesitate to charge for this plugin if it become stable and if you can successfully replicate all from  NOTEPLAN2 (that cost 29$)
- do not tamper the user data between tasks

**Comment by rklasen** [comment]
I would absolutely love that as well.

**Comment by wenlzhang** [comment]
A related proposal:
https://github.com/lynchjames/obsidian-day-planner/issues/10

**Comment by mkschulze** [comment]
Was just about to ask this as well. This would be much appreciated.

**Comment by lynchjames** [comment]
Thanks for your patience on this. I've given these requests and the related proposal in #10 some thought.

From the start, I had deliberately intended the Day Planner to be restricted to task planning during the current day for that day's tasks with elements of a simple pomodoro timer. This meant I made some fairly fundamental design decisions for the plugin on that basis.

I think what is being proposed here and under #10 are really for a separate and much more sophisticated plugin. There is some initial scoping by [tgrosinger](https://github.com/tgrosinger), the author of the [Advanced Tables](https://github.com/tgrosinger/advanced-tables-obsidian) Obsidian plugin, on a plugin that is aimed squarely at these kinds of longer term task and agenda planning requirements, currently named [Agenda for Obsidian](https://github.com/tgrosinger/agenda-obsidian). 

I will be discussing with tgrosinger about my potential contribution to that plugin with some rewritten elements from Day Planner (markdown task parsing, timeline view, status bar, notifications).

@mkschulze I would like to decline your kind donation so that you can review tgrosinger's proposed plugin and consider sponsoring that instead.

**Comment by mkschulze** [comment]
Ok, sounds reasonable. Thx for letting us know!

**Comment by tgrosinger** [comment]
As @lynchjames mentions, a lot of the functionality outlined in the original post is currently included in my plan for [this plugin](https://github.com/tgrosinger/agenda-obsidian). NotePlan has been a big source of inspiration, along with [org-mode](orgmode.org/). I'm still in the planning phase, so it will be a little bit before it's ready. But keep your eye on that repo to follow along. DM me on Discord if you want to be an early access tester or have any feedback. 🙂
