### ISSUE TITLE
Suggestion: allow task-edit/write on dayplanner/weekplanner

### ISSUE THREAD

**Issue by Gewerd-Strauss** [ivan-lednev/obsidian-day-planner#256]
Hello,

I really enjoy the weekplanner so far, but feel like there is significant friction when adding or modifying tasks - you can create a task by clicking on the planner. However, you are then thrust onto the respective date's note; which may or may not open and overwrite a different currently opened note instead. Even without, this procedure is kind of awkward in my opinion.

Would it be possible to edit task entries on the planner itself? F.e. by allowing edit via double-click or F2/whatever key, and then have clicking a timepoint not automatically open the note?

For an example, compare to how the kanban-plugin allows "in-view" editing, and doesn't throw you to its raw-text version when you want to write or edit an entry. Would something similar be possible? 

Thank you.
Sincerely, 
~Gw

**Comment by gmagosta** [comment]
Hi,

I just discovered Day Planner via a blog post and it looks great. I agree with Gewerd-Strauss, however, that working with the week planner is cumbersome, since you can't edit the timeblocks you create without opening the daily files they live inside. Any chance this feature will be added soon? I'd really like to be able to do my time blocking from the weekly view, instead of separately each day.

Thanks!

Gina Marie :)

**Comment by ivan-lednev** [comment]
Hey there! Check out 0.18.0: now hovering over a task with Control pressed will trigger a preview pop-up. This works great with the awesome [Hover Editor plugin](https://github.com/nothingislost/obsidian-hover-editor). This plugin is far superior to any edit modal I would implement 😅

**Comment by ivan-lednev** [comment]
Closing this as stale.
