### ISSUE TITLE
[Feature Request] Option to enable "Track current time" feature from old design.

### ISSUE THREAD

**Issue by utopicchaotica** [ivan-lednev/obsidian-day-planner#281]
The "Track current time" feature was really useful to me to figure out where I was in the day.

I also really like the old colouring for events, but if you could point to me where in the old code it exists, I can probably figure out some CSS witchcraft for myself.

**Comment by ivan-lednev** [comment]
Hello, @utopicchaotica, the old coloring is available and configurable. Check out the settings page.

Can you explain a bit what the "Track current time" feature is? What did it look like?

**Comment by FeralFlora** [comment]
> The "Track current time" feature was really useful to me to figure out where I was in the day.

It's called "Auto-scroll to now" now. I can see why you couldn't find it, though:
1. It's under the gear menu
2. The height of this menu is dependent on the height of the timeline itself. This means you have to make the timeline view very tall in order to actually see the "Auto-scroll to now" toggle. This seems like a bug to me @ivan-lednev, or at least undesirable behavior. The menu should always expand to a height that shows all the options, and if not, there should be a scroll bar (although that seems excessive).

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/33608083/3af3fbf5-32f5-4108-9c5f-d3c3c39ac4f6)

**Comment by ivan-lednev** [comment]
Hi, @FeralFlora, this has been fixed in 0.12.1
