### ISSUE TITLE
Don't want an automatic checkbox

### ISSUE THREAD

**Issue by jimbdeath** [ivan-lednev/obsidian-day-planner#282]
Following the most recent update, it appears impossible to add an item in the timeline without it becoming a "task" with a corresponding checkbox.  Is this the designed behavior?  I personally don't want to add additional tasks to my task list without manually adding the checkbox myself.

**Comment by ivan-lednev** [comment]
Hello, @jimbdeath,

It's explained in the release notes: https://github.com/ivan-lednev/obsidian-day-planner/releases

The plugin now pulls tasks from Dataview cache, and including list items would make this very slow on large vaults or in vaults where everything is a list item (I personally write everything as list items)

**Comment by Rhydderch** [comment]
Could it be a good compromise to only allow list items to be parsed in daily notes?

**Comment by ivan-lednev** [comment]
@Rhydderch, I don't see a way to do this, because Dataview works like this:
1. Get all the list items across the vault
2. Filter out those we don't need

And it's at step 1 that you pay the performance penalty. In big vaults this might mean Obsidian freezing for a couple of seconds after each file update.

If there is some better way to do this, please let me know.

**Comment by jmjeon2** [comment]
Isn't it possible to apply 2 methods below optionally?

1. Parsing list items (or task items) in daily note (just like before v0.11.0, Parsing 1 file would be low cost) 
2. Get all task items in vault (current version's method)

**Comment by Jagdfalke** [comment]
Frankly, I have gone back to v0.10.1 in order to get rid of the check boxes. (Which is sad because I really like the weekly planner). 

Would it be a solution to have an option to choose whether to use the checklist item or list item? 

I might out myself as stupid, but I don't quite understand the performance issue. Why would you want to get all list items from the whole vault when only daily notes are relevant?

**Comment by ivan-lednev** [comment]
@Jagdfalke, as written in the release notes, now tasks are gathered in all the files, not just in daily notes, that's why it might hurt performance: https://github.com/ivan-lednev/obsidian-day-planner/releases/tag/0.11.0

**Comment by Jagdfalke** [comment]
@ivan-lednev Thank you. I've seen the release notes, but I think I am still missing something. 

With the way the planner works at the moment, why do you want to pull from the whole vault? 

Do you plan some cross Integration e.g. with the Tasks plugin? That would make a whole lot of sense and I would totally buy into that idea.

**Comment by ivan-lednev** [comment]
> Do you plan some cross Integration e.g. with the Tasks plugin? 

I'm not just planning it, it has already been done :) It's integrated with Dataview, since it exposes its API to other plugins. Just read the relevant section in the docs: https://github.com/ivan-lednev/obsidian-day-planner#dataview-integration

On the first demo in README you can see it in action: `projects/day-planner-plugin` is in a daily note, and yet scheduled tasks appear in the timeline on the right, because Dataview recognizes them as scheduled:
![main-demo](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/0741bd70-427a-4287-8217-642c4d9d2992)


BTW, It would be awesome if you could point out how I could make this feature more easily discoverable, because I'm getting the impression that people can't easily notice it from the docs.

**Comment by Jagdfalke** [comment]
Haha, okay - I AM stupid. I totally missed the point of this change. This makes day planner more powerful, especially for those who are already invested in Tasks (like I am). This is awesome. I just tried it and this is what I think was still lacking. 

I actually remember scanning through this part of the documentation, but I didn't realize it was what I actually wanted until you just pointed it out to me. 

Me personally, I didn't understand it because of the way I use Tasks (Tasks query in my daily note) and how Day Planner has worked so far (with a dedicated section within a daily note). Maybe the documentation needs to be slightly more elaborate on how Day Planner works now. 

I can try to write somthing up and send you a pull request.

**Comment by weph** [comment]
I have no use for the checkbox either, and the extra tasks create clutter that I don't want. No offense, @ivan-lednev - I see that tasks are valuable for many people, and I understand the performance considerations. I just want to emphasize that @jimbdeath is not alone in his opinion.

The best option would be to allow both, and I'm positive there are efficient ways to do this. I might give it a shot and submit a PR. Any chance you have a demo vault to share that showcases the performance penalty of the old implementation, @ivan-lednev ?

**Comment by arnoesterhuizen** [comment]
An alternative suggestion for the checkboxes: would performance still be impacted if we're able to specify a specific task status?

## My use case

I would like to use the day planner purely for tracking my time logs, not specific scheduled tasks. I use various types of checkboxes, and it would be useful if I could allocate a specific checkbox type for the day planner.

## Example

```md
- [:] 10:00 - 12:00 Some event
- [ ] Non-event-related task
  - [ ] With a subtask, both invisible to the day planner
- [:] 12:00 Another open-ended event
- [:] 14:00 Event
```

Or would that completely defeat the purpose? Or still be unfeasible due to performance issues?

**Comment by weph** [comment]
I finally had some time to dabble around with the old release that still supported regular list items. I created a vault with about 50,000 daily notes and, indeed, browsing the weekly planner was very slow. However, after some profiling I discovered that this was mainly due to some costly operations done repeatedly. After adding some caching, I was able to get the data retrieval from 1500 ms down to 0.3 ms. That said, there's more work to be done. Hopefully, I'll have some time on the weekend.

**Comment by ivan-lednev** [comment]
@weph, I don't think there was an old release that supported both Dataview and plain list items.

**Comment by weph** [comment]
No, there isn't @ivan-lednev 
I worked on 0.10.1 which still supported lists but not yet Dataview. This was just for exploration and to see whether I can tweak it for performance. Next up is the integration into the current release, which will probably be the bigger task since I assume a lot has changed since 0.10.1.

**Comment by ivan-lednev** [comment]
@weph, to save you time, the only thing you need to do is to add `dataview.pages(source).file.lists` here: https://github.com/ivan-lednev/obsidian-day-planner/blob/0a399fabaf1b86f75ecfa626b4de3b4c22650ab3/src/main.ts#L82

After that you only need to make TypeScript happy and probably a couple of other small adjustments, like making sure that scheduled sub-bullets don't show up in the original block, but get into a separate block instead.

**Comment by yodaliu0414** [comment]
@ivan-lednev 
First and foremost, I would like to express my sincere gratitude for your hard work and dedication in developing this add-on. It's clear that a lot of effort and expertise has gone into its creation, and it has significantly contributed to the community.

Regarding the challenges in reading 'list items' within a large vault due to performance concerns, I was curious if you might have considered some alternative approaches. For instance, perhaps not parsing the entire vault, or adopting a strategy similar to the 'Tasks' plugin, where only lines containing a specific tag (e.g., '#tasks') are read? Additionally, in reference to issue #324 (which aligns with my initial understanding), another possibility could be to parse only the sections following a designated title, unless a setting dictates the parsing of the entire vault. While I fully recognize the convenience and utility of being able to access the entire vault's checklist, exploring these alternative methods could potentially offer additional functionalities and benefits. I would greatly appreciate your thoughts on these suggestions.

Thank you once again for your incredible work and for considering my ideas

**Comment by jack-c1xv7h** [comment]
@ivan-lednev 
Would it be possible to add a setting to toggle whether or not the checkmarks are shown in the timeline? This would be a solution for those who just use it for events and not tasks and it wouldnt interfere with how you find tasks/events. Or is this not compatible with how the timeline is built?

**Comment by Mpic** [comment]
Thank you for this plugin, it solves a real struggle for simple and efficient time-blocking and planification.

I'm quite bothered by the checklist style, visually though : it is quite "noisy" to see tasks and timeblocks all with the same checkbox.

Intuitively I would like to set time blocks (that I can put in a template for my daily note : 2h-long worktime blocks, and pauses) and, when I plan my day and as the day goes by, I put tasks and notes in these blocks. 
Maybe I should do it differently : I don't completely get the design philosophy of this new version.

**Comment by Admorei** [comment]
Id also really like the possibility to just place down things into the dayplanner that arent checkboxes ... For me It could also just be the possibility to set them in the settings or something I just dont want to clutter my vault with even more reacurring tasks and such that I need to filter out

At best It would also look for normal list items with a date in the dayplanner section of the daily view only
As far as I understand there is already the pull request by @weph for that but that is way above my paygrade

**Comment by greyivy** [comment]
Also very interested in this functionality. I'd love to block off times of the day and have tasks nested within those blocks (similar to the original screenshots of this plugin under the *Basic editing: create, move, resize (click to expand)* section).

**Comment by Mpic** [comment]
As a workaround, I use tasks like this for time blocks : `- [<]`

Thanks to the Tasks plugin Custom Statuses and the Things theme, this is rendered like this : 

![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/5664276/c2a0c6d1-2168-4064-84dd-7ecad19732dd)

**Comment by hdsateyate** [comment]
Just to add my voice and say:
- I would prefer not to have checkboxes
- I currently have no plans to make use of the DataView integration and would prefer to be able to turn this off to get rid of the extra processing load

Many thanks,

**Comment by ivan-lednev** [comment]
Since 0.17.0, plain list items are recognized in daily notes and added to the timeline.

**Comment by FeralFlora** [comment]
> Since 0.17.0, plain list items are recognized in daily notes and added to the timeline.

As always, there's more than one camp of people and preferences. I would like to exclude list items, and only include tasks. Is that possible currently?

**Comment by Esthetech** [comment]
> Since 0.17.0, plain list items are recognized in daily notes and added to the timeline.

Hey this is great, but dailyplanner is still automatically adding a checkbox instead of a bullet point. It would be great if there would be a setting to change this to your preferred list item (checkbox or bullet point).

The biggest pain it's causing me now is that I'm having a lot of unchecked check boxes that clutter my tasks views where I pull in all my tasks from my vault. I need to uncheck all the events now by hand to not have them show up there.

I would really appreciate if this could be a setting to change.
