### ISSUE TITLE
nested tasks mess up the new drag and drop unscheduled tasks feature

### ISSUE THREAD

**Issue by Rhydderch** [ivan-lednev/obsidian-day-planner#299]
**Describe the bug**
When one has nested tasks inside a scheduled task, they show up as block to be scheduled.
And if you try dragging them things get really laggy.

**To Reproduce**
- create a scheduled task with nested task, see screenshots

**Expected behavior**
Nested tasks shouldn't show up as unscheduled blocks (or at least it should be a setting).
Moreover, it feels like the drag and drop feature is less smooth than before, not to say unusable on my end (trying to drag a scheduled block make things jump around and freeze). I can submit a different bug report if needed.

**Screenshots**
<img width="801" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/3197629/46de1309-16af-461b-9c9d-ec7e3ae790b7">

**Additional context**

**Comment by ivan-lednev** [comment]
Please share a file that causes a slowdown in drag-and-drop.

**Comment by ivan-lednev** [comment]
There is now an option to hide nested tasks

**Comment by Rhydderch** [comment]
> There is now an option to hide nested tasks

Thank you for implementing that feature!
I hid the nested tasks and the menu of the unscheduled tasks, but it seems there is no button yet to show the menu of unscheduled tasks again?

I can't replicate the drag-and-drop lag for now, but I did notice that since a few updates, drag-and-drop takes longer than before to update (at least a few seconds of loading). I will first make sure that the problem is not on my end and will post again if I can replicate it

**Comment by ivan-lednev** [comment]
You can turn them on again in the settings:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/b65782db-993e-4c56-92c7-2a02734401ef)

> but I did notice that since a few updates, drag-and-drop takes longer than before to update (at least a few seconds of loading)

No need to check anything. This is intentional. Here is what is going on:
1. Once you update a task, the plugin writes changes to the file
2. After that, Obsidian waits for a couple of seconds and updates its metadata cache
3. Dataview reacts to the update and updates its cache in turn
4. Day planner notices this and updates it's views

If I let you start editing before step 2 happens, the view is going to reset when day planner finally refreshes, and the task you're editing is going to jump back where it started, which is not good user experience.

**Comment by Rhydderch** [comment]
Thank you for the explanations! That makes a lot of sense. I thought my vault was lagging but now that I know it is part of the process, I don't mind it at all.

By the way, the way you handle subtasks in the plugin is awesome. It really helps with my time-blocking and logging/journaling throughout the day. You really found the perfect balance. And thanks for now ignoring any other checkbox state other than [ ].
<img width="783" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/3197629/525117ca-d064-4f03-8e4b-0f79170f8c61">
