### ISSUE TITLE
Week Planner and Timeline "current time" is wrong after daylight savings

### ISSUE THREAD

**Issue by Esser50K** [ivan-lednev/obsidian-day-planner#301]
**Describe the bug**
The current time in the week planner is 1 hour in front due to daylight savings time.

<img width="306" alt="Screenshot 2023-10-29 at 09 35 34" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/18497570/db7f11fe-117e-41ee-9b21-fdfa139ecdb4">

It is actually 9:30 and the timeline (and week planner) show it as being 10:30.

What's also funny is that if I create a new task on the timeline it is autoshifted 1 hour into the past.

**To Reproduce**
1. Open the "Week Planner"
2. Observe the issue

**Expected behavior**
The current time indicator should be the same as the system time of the device.

**Comment by qiaowuyan** [comment]
Me the same.
Platform: MacOS Ventuna
Time Zone: Central Europe Time (just converted from UTC+2 to UTC+1 because of the end of daylight saving)

**Comment by Rhydderch** [comment]
In case it helps with debugging, here is an illustration of how the change in time affected the timeline:
<img width="778" alt="image" src="https://github.com/ivan-lednev/obsidian-day-planner/assets/3197629/ccb9dc56-1789-48aa-8933-f8602b4b3c82">

However, it might just be temporary (because the change happened during the day), and perhaps tomorrow it will work fine as it will be the first full day on UTC+1.

**Comment by Esser50K** [comment]
@Rhydderch was right, fixed itself. Will close the issue. Solution for everybody, just wait it out 😉
