### ISSUE TITLE
Time position

### ISSUE THREAD

**Issue by marco-ith** [ivan-lednev/obsidian-day-planner#323]
Hi, is it possible to use the time in different position inside the task?

I would like to set it after the title of the task, but if I don't insert the time at the very beginning of the task, I can't see the task in the right spot of the calendar day.

Thank you

**Comment by m-smith** [comment]
I think I have a working start on this, but I feel like some bigger decisions need to be made in order to implement it. As the current parser stands, I think we can have simple times like `- [ ] 10 task` for a task that starts at 10. I'm not sure this will work once we allow things not to be at the start, since if we have a task like `- [ ] buy 2 apples 10`, for buying 2 apples at 10, there isn't really a clear way for us to know which number is the correct time. There are a few options I see as solving this.

My current implementation just enforces that, if the time is not at the start, it must have a strict `HH:mm - HH:mm` format. If we want to include these simpler time formats, I think it's neccessary to demark the time with delimiters, if they are not at the start. I can imagine the following options:
- **strict format**, as discussed: `HH:mm - HH:mm`
- **dataview-style** : `[day-plan:: ${time}]`
- **our own delimiters**: `[@ ${time}]`
- **tasks emoji style** `⏱️ ${time}` 

to accomplish this. Maybe best would be to try and support all four? Not sure @ is a good delimiter as it is a shortcut for nl-dates plugin so irritating to type. Also not sure ⏱️ is the right emoji, maybe we can add a setting for a custom choice?

Let me know what you are thinking!

**Comment by m-smith** [comment]
There is also the issue of what to default to and where when adding times to tasks without time. I guess we could have a setting again to add the chosen format to the end of the string, before any task / reminder signifiers.

**Comment by ivan-lednev** [comment]
Hello, @m-smith,

Dataview format is the way to go here, since it's the easiest to implement -- Dataview will give you the value of the prop without the need to parse it yourself. I think `[time::18:00-19:00]` is a good one.

**Comment by ivan-lednev** [comment]
Available in 0.23.2
