### ISSUE TITLE
Task notification not working

### ISSUE THREAD

**Issue by kmaustral** [ivan-lednev/obsidian-day-planner#334]
In 0.16, the status bar is fully restored and working well, thank you. One minor improvement is to give the option to include the time of the next task, rather than minutes left. 

I'm still not getting task notifications as happened before in previous versions. I'm on Windows 11.

**Comment by nmariano9** [comment]
Also not getting task notifications anymore! Using Ventura 13.4.1.

**Comment by aurerua** [comment]
I also don't get notifications on macOS Sonoma 14.12.1.

**Comment by clinzy25** [comment]
Same here Ventura 13.6.3

**Comment by ScribbleTAS** [comment]
Since notifications are really important for my use case with this plugin, I took a look if I could find out what was wrong, because it neither showed up on Windows 10 or Windows 11...

To my understanding, the setting for the task notification is not connected to anything currently, so it just does nothing in the code and I think I understand why...
  
I don't have any experience with obsidian plugin development and svelte, but I think there is just no good way to trigger this notification...  
My best guess was to:
1. Check the day planner file each minute,
2. iterate through the tasks,
3. parse the start date and compare that to the current time,
4. if true fire a notification...
 
A truly horrible way to do it, so I discarded that idea... Didn't even work because I used the wrong method and instead got all tasks in every file across the vault and checked that... And since I have many repeating times in my day planner, this fired way too many notifications

**Comment by ivan-lednev** [comment]
Hello, @ScribbleTAS, 

this is not a bad guess actually 😄. The notification functionality got deleted when I refactored one of the components from pure JS into Svelte. Since this is such an important feature for users, I'll re-add it soon.

**Comment by ivan-lednev** [comment]
Please update the plugin and re-check.

**Comment by ScribbleTAS** [comment]
> Please update the plugin and re-check.

Tested on Win 10 and Win 11, works like a charm, thank you very much 👍
