### ISSUE TITLE
Tasks no longer showing on Day/Week Planners after update

### ISSUE THREAD

**Issue by drbswa** [ivan-lednev/obsidian-day-planner#367]
After the latest update (0.17.2), tasks on my daily note that are aggregated and displayed from the Tasks plugin no longer appear on the Week or Day Planner,.

This is what the block on my daily notes would look like
````
### Time Blocking
```tasks
scheduled on 2024-02-19
group by status reverse
sort by description
```
````

Which looks like this in the note:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/60708741/24f31c6f-9815-471e-a06e-2fb55858abd9)

It showed there this morning until I updated to the latest version.

I'm hoping this is a minor fix as I appreciate the convenience of not having to enter in my recurring meetings every single day they happen.

**Comment by ivan-lednev** [comment]
Hello, @drbswa,

This is because from 0.17.0, pulling tasks from files other than daily notes is opt-in, to improve performance.

The best solution is to add the tag you use for task files to the Dataview filter, like so:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/bd4c6ad2-ab4f-48c0-931d-e42fd17c226d)

You can also add folders this way.

**Comment by drbswa** [comment]
Ah, I see. I saw mention of Dataview source on the README, but I guess I just wasn't observant enough to figure out where this actually was. Thank you!
