### ISSUE TITLE
A task that is created on a different daily note is not shown in the time line

### ISSUE THREAD

**Issue by shunichironomura** [ivan-lednev/obsidian-day-planner#392]
**Describe the bug**
A task created on 2024-03-01's daily note (for example) and scheduled on 2024-03-02 using the emoji format is not shown in the timeline of 2024-03-02.

**To Reproduce**
1. Create a task on a daily note and schedule it for a different day; for example, write the following inside the 2024-03-01's daily note:
```md
- [ ] A task ⏳ 2024-03-02
```
2. See the timeline for 2024-03-02. Ensure `Show unscheduled tasks` option is enabled.

**Expected behavior**
The created task is shown in the unscheduled tasks section of the 2024-03-02 timeline.

**Actual behavior**
The task is not shown.

**Additional context**
[Workaround]: If I add "Day Planners" (the name of the folder where I put my daily notes) to the `Include additional files, folders, and tags with a Dataview Source:` setting, the task appears. My impression was it is not necessary since it says, "Tasks are pulled only from daily notes."

**Comment by chenyangh** [comment]
Having the same `asks are pulled only from daily notes` issue

**Comment by ivan-lednev** [comment]
Hello @shunichironomura,

The reason is this: 'daily notes' and 'tasks with ⏳' are two distinct modes.

If we have a file called `2020-01-01.md` with this task:

```md
- [ ] Wake up  ⏳ 2020-01-03
```

The task has 2 `scheduled` dates: one from the file name, and one from the ⏳ emoji.

If your Dataview filter is empty, as it is by default, day-planner is going to rely only on the date from the file name, and it's going to ignore any tasks with the hourglass emoji.

**Comment by bayerju** [comment]
But even if the dataview filter is not empty it does not work properly. 
I belief the reason is the [use-tasks-from-extra-sources.ts](https://github.com/ivan-lednev/obsidian-day-planner/blob/5ae2272febc5e643515a70588037f4a9fd4def0b/src/ui/hooks/use-tasks-from-extra-sources.ts#L29C7-L33C1). If I delete this code and use the $dataviewsource directly, it works for me. But I am not sure if it would break anything.

If @ivan-lednev  is fine with that I could prepare a pullrequest with that change.

**Comment by shunichironomura** [comment]
@ivan-lednev Thank you for the clarification. Then I think it's not a bug but rather I misinterpreted the sentence "Tasks are pulled only from daily notes."

I now understand that it actually means "tasks are pulled from a) the daily note of the same day, and b) the dataview filter." If that's the case, it's working as expected for me.

I thought it would be nice if the documentation could be clearer on this, but it seems like it's already updated. Thank you!

**Comment by ivan-lednev** [comment]
Hey, @bayerju, if you find that the plugin is still inconsistent after the latest update, please respond in this ticket.
