### ISSUE TITLE
[Feature Request] Show the calendar events in the daily note

### ISSUE THREAD

**Issue by vintersnow** [ivan-lednev/obsidian-day-planner#406]
Thank you for adding the calendar sync feature! It is awesome!

I want to see the events on the daily note itself.
Is there any way to do that? (like searching with dataview)

**Comment by bitskc** [comment]
I would love this as well.  Would be nice if actually copied the events to the daily note (and sync changes from the remote calendar). I think this could be done with the iCal plugin, but would be nice to not have to rely on multiple plugins.

**Comment by ivan-lednev** [comment]
There is another plugin that does exactly this: https://github.com/cloud-atlas-ai/obsidian-ics. If possible, I'd like to defer different workflows to other plugins if they already exist and work well.

**Comment by j-peeters** [comment]
I would like to add my thoughts regarding implementing this feature into Day Planner.
I have tested ICS and to get the events into your daily note you have to import them. This works well but if you also use the Remote Calendars functionality in Day Planner (which is a much better and nicer implementation than ICS because of its color coding) events are shown twice. If the in-note display of remote calendars from Day Planner would be supported everything would stay nice and clean and give a good overview over your events in one place in the note. Thanks for considering.

**Comment by lmachineone** [comment]
+1 on this one if possible would really love to have this implemented
