### ISSUE TITLE
problem with sync task query in daily notes to day planner timeline

### ISSUE THREAD

**Issue by Chung-Hwan** [ivan-lednev/obsidian-day-planner#410]
I used to use day planner with my daily note template composed of tasks queries. after I reinstall the plugins(tasks,dayplanner,periodic note) the tasks in my day planner doesn't sync with day planner timeline. is it issue of version of day planner or my setting?

![스크린샷 2024-04-03 오전 12 30 27](https://github.com/ivan-lednev/obsidian-day-planner/assets/153967767/1e22cd68-fc26-4deb-9759-d044a500e072)
![스크린샷 2024-04-03 오전 12 30 50](https://github.com/ivan-lednev/obsidian-day-planner/assets/153967767/b2ce8d0d-62fe-40d2-a7ad-5557e9ed00f4)

**Comment by ivan-lednev** [comment]
Hello there. The issue here is that now by default the plugin does as little work as possible, that is, it reads directly from the daily notes. If you use some global filter for the obsidian-tasks-plugin, like a `#task` tag, just add the same tag to the dataview filter of the planner:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/dbf461ad-d54f-4723-aacc-ce7331c9d43e)
