### ISSUE TITLE
Onload Error

### ISSUE THREAD

**Issue by moooooo16** [ivan-lednev/obsidian-day-planner#426]
**Describe the bug**
Below error shows during on-load, and lead to all funciton freeze.

```js
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'children')
    at t.getSideLeaf (app.js:1:2222985)
    at t.getRightLeaf (app.js:1:2221766)
    at DayPlanner.initTimelineLeafSilently (plugin:obsidian-day-planner:49154:32)
    at async DayPlanner.onload (plugin:obsidian-day-planner:49193:5)
```

**To Reproduce**
1. Create new vault
2. Download community plugin Day planner
3. refresh obsidian
4. Error display in console

**Expected behavior**
No error 

**Screenshots**
![Screenshot 2024-04-10 at 06 30 18](https://github.com/ivan-lednev/obsidian-day-planner/assets/78249781/f33bfad3-e337-41c9-aafc-d6ef95226afa)

**Comment by kjarnot** [comment]
I'm having the same issue.  This may be related to an issue I've been having where the day planner interface stops responding/updating.

**Comment by sepatel** [comment]
> I'm having the same issue. This may be related to an issue I've been having where the day planner interface stops responding/updating.

I just created a bug report for why that stopping issue was happening for me https://github.com/ivan-lednev/obsidian-day-planner/issues/438

It might be the same for you I don't know. But while this particular this is annoying, I haven't yet figured out what the collateral damage of this issue is. But I would still like to see this one get fixed.

**Comment by cheeetoo** [comment]
I am having this error on the latest version of everything. Has this been fixed for others?
