### ISSUE TITLE
Any link, and the text after, is stripped from the task when dragged to a new time.

### ISSUE THREAD

**Issue by gypsyav** [ivan-lednev/obsidian-day-planner#447]
**Describe the bug**
When there is a link in a task description the link and all text after it is removed when dragging the task to a new time. It also doesn't appear in the planner view.

**To Reproduce**
1. Add a task with a link such as "go [[here]] for more info"
2. In the planner notice it will only display "go" 
3. Drag the task to a new time
4. The original task now reads "go" with no link or text after

**Expected behavior**
Links appear in planner and are not stripped from the task when it is moved.

**Comment by pancan21** [comment]
Hey @gypsyav this is unfortunately not reproducible with the steps you provided.
But I reproduced the behavior with additional information:

As long as the task does not end with something like  [completion:: 2024-06-12] as done when checking the box with the Tasks plugin enabled, it seems to work fine. To be precise whenever the regex"\\[.\*::.\*\\]"gm appears anywhere in the text, only the text before the first bracket is recognized.

This is probably caused by line 40 in src/regexp.ts:
export const propRegexp = /\[(.+)::(.*)]/g;

Which is used by line 17-19 in src/util/properties.ts:
export function deleteProps(line: string) {
  return line.replaceAll(propRegexp, "").trim();
}

@ivan-lednev  As I am not a typescript expert I am not confident enough to fix it myself...

The issue seems to be related to #434

**Comment by ivan-lednev** [comment]
Please update and re-check.

**Comment by pancan21** [comment]
The issue is still persisting for me with 0.25.0

Here and example to reproduce it:
Add this to the planner section
- [x] 19:00 - 19:30 Reproduce issue [[Some Link]]  [completion:: 2024-11-04]

You should first of all see that only "19:00 - 19:30 Reproduce issue" is shown in the day planner widget and that as soon as you drag this only the text shown remains in the note cutting of the link and the completion date dataview property.
