### ISSUE TITLE
Advanced Editing with ctrl and shift not working.

### ISSUE THREAD

**Issue by StevieWonder92** [ivan-lednev/obsidian-day-planner#462]
**Describe the bug**
When holding ctrl and moving items around, the dots don't change to stacks and the items move just next to each other. 

**To Reproduce**
1. Add items to timeline
2. Hold down ctrl button and click and hold upper right corner of item
3. Move item
4. Item moves next to latter item

**Expected behavior**
Both items should move to a later time and not next to each other.

**Screenshots**
![grafik](https://github.com/ivan-lednev/obsidian-day-planner/assets/167410993/7c3eea8c-3295-4405-81b6-5785633d8528)
![grafik](https://github.com/ivan-lednev/obsidian-day-planner/assets/167410993/62146c7a-b03d-42b0-9355-119792af7e4a)

**Additional context**
Version 0.20.4

**Comment by hadimohamed1** [comment]
Same issue

**Comment by leafybees** [comment]
Also same issue

**Comment by Stauros-Nicod** [comment]
Same

**Comment by ivan-lednev** [comment]
Advanced edit controls have been moved to a separate widget to avoid conflicts with the hover editor behavior and to be compatible with mobile devices in the future:
![image](https://github.com/ivan-lednev/obsidian-day-planner/assets/41428836/0c931ae1-4f69-4264-b3a0-0dfd4e462b18)

I removed the confusing bit from the docs.

**Comment by Stauros-Nicod** [comment]
Please, find another solution, maybe add different zones on the items so that when dragged from specific zones - it would duplicate. Right now it's close to unusable - I need to move the mouse away from the task, click on the button with crossed arrows, move the mouse, click on "copy on drag", move the mouse back to the task item, do the action, move the mouse back to the "Move on drag", another click, then move to the button with crossed arrows and click. If I messed up and didn't move the item to the needed place, my automatic reaction is to drag it right away to the correct place, but now it just makes a third copy. It's so unintuitive that it's easier to just copy-paste text and edit time manually afterwards.

**Comment by Stauros-Nicod** [comment]
It would be possible to work around by getting used to always duplicate with drag and drop and moving items by moving separately the start of the task and the end of the task - but it's currently impossible to move the start of the task. So the only solution right now is to constantly switch "Copy on drag" on and off for every specific action you take.

**Comment by ivan-lednev** [comment]
Fixed in 0.21.1. Now there are separate controls for different modes right on the task block.
