### ISSUE TITLE
[Feature Request] Time tracking and time boxing enhancements

### ISSUE THREAD

**Issue by DeveloperMarius** [ivan-lednev/obsidian-day-planner#486]
Hello,
my goal is to add better time boxing and task time tracking capabilities to obsidian. Day Planner has enabled myself to plan my day better but there are some issues/ enhancements I would like to address. I do not want to just create this issue, but I am also looking forward helping to implement parts where my help is wanted.

- -I have problems creating tasks in my daily note that are for another day. (EXAMPLE WILL FOLLOW SOON HERE). Is this an expected behavior or not? I haven't looked at the code yet, maybe you could show me the specific part where the problem lies.

- -I would love to see Day Planner to respect recurring tasks in advance. Currently Day Planner only shows tasks that are created. But recurring tasks are only created when the last task is completed. I hope you see the problem here, because I cannot Plan weeks in advance, when I'm not seeing all my recurring tasks. Yes I could implement daily recurring tasks in my daily template, but that wouldn't be a great solution.

- -I'm currently not seeing a standardized way to store intervals someone worked on a task. In #330 you mentioned one example of a format, but for example eatgrass/obsidian-pomodoro-timer has a completely different approach to the problem. I also don't know if it would be a better idea to implement these formats directly into the obsidian-tasks plugin. I hope @claremacrae joins this discussion/ issue and shares her ideas. Maybe something from https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2502 could be helpful.

I saw that your tracker branch is inactive for some time but I would love to see the feature shown in https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2502 released into production.
I'm looking forward to your feedback and hope that we find a solution that we can then code into the respective plugin. Each plugin should focus on its core capabilities.

Thank you.

~ Marius

**Comment by claremacrae** [comment]
I don't have enough context to understand this, but since I've been mentioned, I will reply...

> Time tracking and time boxing enhancements

It's not my plugin, but personally I think this should be multiple much-smaller requests.

My advice to users is that if it is not possible to understand the specific request from the title, then the request is too large, and is unlikely to be definable or implemented.

"Time tracking and time boxing enhancements" is very vague and non-specific....

So sorry, but I won't be spending my limited time engaging in this discussion.

Also, please note the status of the referenced Tasks issue: Closed as not-planned
- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2502

See also:

- https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2721

**Comment by DeveloperMarius** [comment]
Hello,
thank you for the fast reply. I will separate this into multiple issues. Furthermore I will not reference the tasks plugin anymore, because of obvious reasons stated in your referenced issue about the separation of task and time tracking.

~ Marius

**Comment by claremacrae** [comment]
@DeveloperMarius Thanks very much.

It may be that Tasks can help support the implementation of _some_ aspects of this, such as perhaps allowed its date fields to have optional time values...

That definitely would be in-scope for tasks, and we have lots of requests for that, including:

- https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/64

So I will be very happy to be mentioned in more focussed issues at the appropriate time...
