### ISSUE TITLE
Timeline Only Shows Events that are Specified in 24h Time 

### ISSUE THREAD

**Issue by Beatzoid** [ivan-lednev/obsidian-day-planner#501]
**Describe the bug**
When I specify an event in the day planner, if I don't put it into 24h time, it doesn't show up on the timeline

**To Reproduce**
1. Create an event from 14:00 - 15:00; notice that it shows up correctly
2. Create an event from 2:00 - 3:00 (same time as step 1, just 12h); notice that it doesn't show up

**Expected behavior**
It shows up the same as it does with 24h time

**Screenshots**

<img width="1077" alt="Screenshot 2024-07-22 at 11 24 49 AM" src="https://github.com/user-attachments/assets/41661cde-a262-4ec1-82db-579c3fac6e46">

**Additional context**

The other plugins I have installed are Dataview, Iconize, and Tag Wrangler. I have also checked and made sure that all installed plugins and obsidian are on the latest version.

**Comment by Beatzoid** [comment]
Another side effect of this bug that I just found is that when you have the "Default Timestamp Format" set to "hh:mm" (12h time) and you reorder an event on the timeline, it will change the markdown to be 12h as well, and therefore it will disappear from the timeline.

**Comment by technotherion** [comment]
In my experience, it's not disappearing from the timeline, rather appearing at the AM time. E.g. an event set for 2PM will show up at 2AM. 

EDIT: I found a solution for anyone else having this issue. 
Change the time format to "hh:mmA" INSTEAD of "hh:mm" and the AM/PM part will be correctly parsed. 

I suggest to the plugin creator to change the hint text in Default Timestamp Format to suggest that people use "hh:mmA" instead of "hh:mm".

**Comment by ivan-lednev** [comment]
This isn't a bug. It's more like a limitation of this time format: `2:00` is ambiguous if you don't add `am/pm` to it. So you should follow the advice above:
>  Change the time format to "hh:mmA" INSTEAD of "hh:mm" and the AM/PM part will be correctly parsed.
