### ISSUE TITLE
Day Planner plugin frozen on mobile devices

### ISSUE THREAD

**Issue by Drandra** [ivan-lednev/obsidian-day-planner#519]
On both my phone and tablet, I initially had the ability to drag and drop, but now the tasks are totally frozen. It doesn't update if I change times in the daily note until I restart the app and I can't interact with any of the tasks.

I've checked it on both minimal theme and typewriter theme. I've also reinstalled the plugin.

**Comment by ivan-lednev** [comment]
Hello, @Drandra, which device are you on?

**Comment by andyholst** [comment]
I get micro freeze when I have the Day Planner plugin enabled. The only plugin on Obsidian that causes micro freeze when I type on my developer laptop with it enabled. I get serious long performance issues on my Android phone. Are you guys considering doing some code performance refactoring improvements?

**Comment by ivan-lednev** [comment]
Hello, @andyholst, this should be a separate issue, since what you're describing is not what this issue is about.

Please create a separate issue and specify:
1. How many remote calendars are you using and how old/big they are (i.e. how many events they contain)
2. What Dataview filter are you using

**Comment by ivan-lednev** [comment]
Please update & re-check.
