### ISSUE TITLE
Deleted events in google calendar are not refreshed

### ISSUE THREAD

**Issue by supeters** [ivan-lednev/obsidian-day-planner#530]
**Describe the bug**
I deleted a event in the google calendar - but it does not refresh in the day planner

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by puchasa** [comment]
I have the same issue on outlook calendar and I think I know what the problem is: Recurring events where only a certain event but not the entire series was removed from the calendar.

Tests that led me to this conclusion:

- Does not seem to be a problem with the (day planner plugin's) cache: I downloaded the plugin and imported the calendar today and events that were already canceled still show up in obsidian. (could technically still be calendar cache making problems).
- Created and removed an event from my calendar. Showed up and disappeared as expected (and with remarkably little delay!).
- Created a recurring event and removed one occurence: Recurring AND removed events shows up. All events disappear when I delete the recurring event series.

It is important to note that my outlook calendar on both desktop applications, mobile apps and web interface do NOT share this issue.

Additional information: I believe the behaviour persists no matter whether you or others have created the series (this i have confirmed) and no matter whether the organizer has cancelled an occurence or you personally have declined a specific occurence (I'm pretty sure I have examples of both in my calendar, but I have not tested (because I'm not messing with coworkers' calendars)).
Just for the sake of it I also attempted to import my calendar via this (https://github.com/ivan-lednev/obsidian-day-planner/issues/395) method instead. Same issue.
