### ISSUE TITLE
Feature request: Allow Gantt events that go past midnight

### ISSUE THREAD

**Issue by masasin** [ivan-lednev/obsidian-day-planner#58]
Some events go past midnight or take more than 24 hours (e.g., flights or shift work). Is it possible to make it so that e.g., 00:30 appearing later in the list be considered as part of the next physical day, while still being part of the same logical day? I've managed to do that by using 24:30 as the next start time, but the Gantt chart doesn't know how to plot that correctly, and puts it at the current time. (The main timeline handles them perfectly, even if I put a 00:30 start time and a 4:00 end time.)

**Comment by lwb52** [comment]
I am making a separate but related request to allow Gantt modification to take place on any day, so that revisions to the schedule can be calculated in the chart after midnight or even many days later. (If validation is needed, for teams or work purposes, then the latest ”calculation” time-stamp could always be added automatically at the bottom of the chart.)

**Comment by barbosarp** [comment]
+1

**Comment by ivan-lednev** [comment]
Mermaid diagram support has been removed.
