### ISSUE TITLE
Feature Request: Render Markdown in timeline

### ISSUE THREAD

**Issue by deathau** [ivan-lednev/obsidian-day-planner#83]
It would be great if the markdown of a task would render in the timeline. I often use bold/italic to indicate certain things, and often link to related pages for specific tasks. Having those render properly in the timeline would not only look nicer, but in the case of links, actually be quite useful.

**Comment by balint-bg** [comment]
This would be hugely appreciated, yes please! I have to manually juggle my notes to make sure no links are in the timeline because they render badly in the gantt chart. Would be awesome to have e.g. clickable links in the gantt diagrams, and yes italic and bold and code formatting would be nice too.

**Comment by 6-AND-9** [comment]
+1

**Comment by ivan-lednev** [comment]
Fixed in 0.7.0.
